name: Node.js CI

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.15.3]

    steps:
    - name: Checkout code
      uses: actions/checkout@v1
    - name: NPM install
      uses: bahmutov/npm-install@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    # Needs to be before the try build step since it prunes dependencies
    - name: Test
      run: npm test
      env:
        CI: true
    - name: Build
      run: npm run build
      env:
        CI: false # TODO Linting errors cause the build to fail when CI is true (default)
